export {
  assertGrant,
  authorizationError,
  AuthorizationError,
  decode,
  encode,
  coversDomain,
  Grant,
  includeDomains,
  removeDomain as removeDomainFromGrant,
  Schema,
  validate,
} from "./connection.ts";
export type { Connection, StoredCredential } from "./connection.ts";
export {
  complete,
  Error,
  extend,
  Method,
  removeDomain,
  RemoveDomainResult,
  start,
  StartResult,
} from "./connect.ts";
export type {
  Authentication,
  AuthenticationFailure,
  BaseInput,
  CompleteInput,
  Continuation,
  ContinuationStore,
  Failure,
  InteractiveFlow,
  InteractiveStart,
  ExtendInput,
  Method as ConnectionMethod,
  Requirements,
  RemoveDomainInput,
  RemoveDomainResult as ConnectionRemoveDomainResult,
  StartResult as ConnectionStartResult,
} from "./connect.ts";
